Use `fs_err` for better file operation error message
[fs_err](https://crates.io/crates/fs-err) is drop-in replacement for `std::fs`, that provides more helpful messages on errors.

Take #727 as an exmaple,

before:
```
error: No such file or directory (os error 2)
```

after:
```
error: failed to create file `/tmp/rye/config.toml`

Caused by:
    No such file or directory (os error 2)
```